### ISSUE TITLE
Doesn't work with Bower

### ISSUE THREAD

**Issue by smiller171** [pimterry/lambda-git#1]
Bower needs [ls-remote](https://git-scm.com/docs/git-ls-remote.html) to work

update: I see you are shipping ls-remote, but bower isn't working. Trying to understand why

```
Error --------------------------------------------------

     Failed to execute "git ls-remote --tags --heads https://github.com/angular-ui/bootstrap-bower.git",
     exit code of #128
fatal: Unable to find remote helper
     for 'https'
```

**Comment by pimterry** [comment]
Hi @smiller171! I have no idea why this is, and to be honest I'm not really maintaining this. I don't need it myself any more, and it's just a tiny wrapper around an extracted git implementation from LambCI: https://github.com/lambci/lambci/tree/master/vendor. Any problems with the git implementation, rather than the wrapper, aren't really something I can help with.

I would _love_ PRs though. Are you interested in taking a look at this?

**Comment by smiller171** [comment]
I'm taking a look at it now. Looks like git just needs to be compiled with curl-devel. http://stackoverflow.com/questions/8329485/unable-to-find-remote-helper-for-https-during-git-clone

**Comment by ryanblock** [comment]
Hey @smiller171, is this still an active issue? Did you find a workaround?

**Comment by smiller171** [comment]
I no longer remember what I was using this for or if I found a solution. I probably just found an alternative for whatever I was doing.

**Comment by ryanblock** [comment]
__
