### ISSUE TITLE
can't find the cloned repo 

### ISSUE THREAD

**Issue by rezarajabii** [pimterry/lambda-git#11]
I would like to download a repo and zip it via a lambda , however after cloning the repo I can not find the repo, in order to be able to zip it : 

```
  require("lambda-git")({
      targetDirectory: "/tmp"
    })
    .then(function (env) {
      // git is now ready
      console.log('running git commands : ')
      exec("git clone --quiet https://github.com/pimterry/lambda-git.git");
    })
    .catch(function (error) {
      // something failed
      console.log('error with the git commands', error);
    });
```

**Comment by pimterry** [comment]
If you're not hitting an issue where `git` doesn't exist or throws some error starting up, then this is unlikely to be related to `lambda-git` directly, but an issue with how your code uses git itself, so I'm going to mark this issue as closed.

That said, looking at your code I suspect the problem is that you're not waiting for `git clone` to complete. Your call to `exec()` is asynchronous, and you need to wait until the clone finishes somehow. You probably want to pass a callback, and only try to zip it once that's been called successfully: https://nodejs.org/api/child_process.html#child_process_child_process_exec_command_options_callback.
