### ISSUE TITLE
No binaries when untar on lambda

### ISSUE THREAD

**Issue by mnapoli** [pimterry/lambda-git#3]
When the code runs on a Lambda there are no binaries extracted. What I mean by that is that the `/tmp/git/usr/bin` directory exists, but it's empty.

I have no idea why the untar doesn't work :/ My goal is to get git running on a lambda, if you have any other solution I would be very thankful :)

**Comment by pimterry** [comment]
Sorry for the delay @mnapoli - I have no idea why this would happen.

This library is just a tiny wrapper around the git build from https://github.com/lambci/lambci/tree/master/vendor, and I'm not actually using it myself any more, since I'm not working on any Lambda projects. I'm struggling to imagine what might be going wrong though, the extraction code is _very_ simple: https://github.com/pimterry/lambda-git/blob/master/index.js#L25-L27. You've clearly started extracting (because `usr/bin` exists), but something in that process has failed.

There was a new release recently - can you reproduce this with both versions `0.1.0` and `0.1.1`? If you're using `0.1.1`, does the promise returned resolve successfully?

**Comment by mnapoli** [comment]
OK I'm very sorry, this is the kind of embarrassing issue you open when you're completely lost if front of a problem, blaming someone else, but actually… I think something went wrong with the first extraction (for some reason). Then the lambda instance was reused and the `git` directory was still there, my script would avoid extracting the archive again and I was looking at the same directory every time…

And of course I forgot to come back here and close this issue :)

Anyway thanks for this repository, it was helpful!
