### ISSUE TITLE
No such file or directory, open 'git-2.4.3.tar'

### ISSUE THREAD

**Issue by JasonEtco** [pimterry/lambda-git#6]
Hello! I'm encountering an issue when running a Lambda function; it throws this error:

```
Error: ENOENT: no such file or directory, open '/git-2.4.3.tar'
```

Here's the basic function:

```js
const execa = require('execa')

module.exports.pusher = function (event, context, callback) {
  require('lambda-git')()

  try {
    execa('git', ['--version']).then(result => {
      console.log(result.stdout)
      result = result.stdout
    })

    const res = {
      statusCode: 200,
      body: JSON.stringify({
        message: 'Executed',
      })
    }
    callback(null, res)
  } catch (err) {
    console.log(err)
    callback(err)
  }
}
```

I tried moving the `require('lambda-git')()` outside of the function, same result.

Any ideas? I'd really appreciate your help 🙏

**Comment by pimterry** [comment]
Sounds like it hasn't been installed correctly somehow. That error is probably that the tar file containing git is not present in the same path as lambda git's index.js (though the full stack trace would make it easier to know that). You should end up with a node_modules folder that looks something like:

```
node_modules/lambda-git
 - index.js
 - git-2.4.3.tar
```

That's certainly what's currently inside the package: https://unpkg.com/lambda-git@0.1.1/

How are you installing lambda git? Can you check the files you have on disk before this happens, and see whether the tar file really is present?

**Comment by JasonEtco** [comment]
Coming back the next day, I've realized it's probably due to my Serverless setup using Webpack. I don't think Webpack is moving over the `.tar` file in the "compiled" lambda function. I can probably do without Webpack, I had originally needed it for size constraints but I'll see what I can do.

In any case, I'm 95% sure thats whats causing my issue, so I'm going to go ahead and close this. Thanks!

**Comment by pimterry** [comment]
Yep, webpack causing this sounds very very likely to me.

**Comment by orrybaram** [comment]
@JasonEtco what did you end up doing? I tried switching to `serverless-plugin-typescript` but the build times were very slow.

**Comment by pimterry** [comment]
@orrybaram I can't be sure, but it from the above it sounds like he stopped using Webpack entirely.

The underlying problem here is that lambda-git expects the `git-2.4.3.tar` file to be available, and webpack doesn't know that (Webpack only bundles files based on `require` calls, and ignores fs.createReadStream calls like we're using here: https://github.com/pimterry/lambda-git/blob/master/index.js#L25).

If you need Webpack in your build, you'll need to explicitly tell Webpack to handle this for you.

It should be fairly simple to do I think, you just need to ensure that in your final deployment lambda-git's `git-2.4.3.tar` file is in the same folder as the bundle that contains `lambda-git`. It's hard to provide much more specific advice without looking at your config, but I suspect a simple setup with [CopyPlugin](https://github.com/webpack-contrib/copy-webpack-plugin#copy-webpack-plugin) should be able to copy that file across for you.

**Comment by orrybaram** [comment]
@pimterry Thanks for the advice! Sounds like that could definitely work. In the meantime I've been using vanilla js 😝. Will give this a shot when I have some time though.
